textileio/photos

App/Containers/PhotoViewerScreen.js, package.json, yarn.lock
Point at fork of the image viewer lib to get a bug fix, hack in a working viewer for now. Loading thumb image data to cut down on memory usage until our URI based approach is ready. 
Be sure to `yarn install` to get the image view lib fork in there.
=> Temp image viewer fix

App/Containers/OnboardingCheck.js, App/Containers/TextileManager.js, App/Containers/TextilePhotos.js, App/Navigation/AppNavigation.js, App/Navigation/PhotosNavigation.js
We have a bunch of event listeners that are used to trigger photo queries and update state of photo data. They were all created as part of `TextilePhotos.js`, which is really just the UI for viewing the photo grid. This isn't good design, and it makes the photo grid impossible to re-use. 
This PR does two things:
1. Move all event listeners and redux triggers to a wrapper component, keeping `TextilePhotos.js` more general use and more reusable.
2. Create a tabbed interface for now that we can plug the first cut of shared photos into. It will look something like:
That isn't the end design or anything, just a place to start for early testers.
=> Refactor out non-UI event listeners, tabbed UI

App/Redux/IpfsNodeRedux.js, App/Sagas/StartupSagas.js, App/Sagas/TextileSagas.js, App/Sagas/index.js
Split out node creation redux so it can be created immediately and started later, supports sign up / log in.
Current setup, created the node as quickly as possible and then starts it if onboarding is complete. If onboarding is incomplete, it starts the node after onboarding.
=> Create node immediately, start in possibly immediately, def after onboarding

App/Containers/TextileManager.js, App/Redux/IpfsNodeRedux.js, App/Sagas/StartupSagas.js, App/Sagas/TextileSagas.js, App/Sagas/index.js
Hack to detect when the app enters the foreground from cold start in a release build. I don't love this as a long term solution, but it should work for now. 
The key to the hack is that I found a particular pattern of behavior from `AppState` api when the app is launched into the foreground from a terminated state. We map this specific behavior to a 'foreground' event.
Let's be sure to test this on android as well, i've only tried iOS so far.
=> Fix Release Build Node Start

App/Containers/PhotoViewerScreen.js
These were causing issues with rendering on Android. Thanks to @andrewxhill for discovering the fix. Since switching to a view instead of SVG, this should be consistent on both iOS and Android.
Fixes #111.
=> Removes SVG and Rect elements

App/Services/PhotoUtils.js
Big one. This fixes the crash we were seeing when adding images from camera roll on a real device.
=> Give asset lib file copy and explicit JPG extesion

App/Containers/Styles/TextilePhotosStyle.js, App/Containers/TextilePhotos.js, App/Navigation/PhotosNavigation.js, App/Redux/TextileRedux.js
This adds a 'preferences' key to our persistent Redux. Right now the only key in there is `verboseUi`. When `verboseUi` is `true`, we can chose to render more data into the UI. For now, I display the node state at the bottom of the photo grid so you can see it even when there are photos in the grid.
=> Node status viz

App/Config/ReduxPersist.js
Turns out the behavior of redux-persist is to overwrite your initial state (and any changes/additions you make to it in, for example, `TextileRedux.js`) with whatever was persisted previously. This explains why the `textile.preferences.verboseUi` key wasn't present when updating to the version of the app that added it to `TextileRedux.js`... The previously persisted data didn't contain that key.
The answer: Migration.
This looks like a tiny change, but I dug deep into understanding how redux, redux-persist, seamless-immutable and migrations all work together. Pretty tricky stuff, but now that I understand it, we're gold for migrating persisted data in the future.
=> Preferences persistence migration

App/Sagas/TextileSagas.js, TextileIPFSNativeModule.js, ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h, ios/NativeModules/TextileIPFS.m
I had @andrewxhill sneak the sagas change into the App Store release because, without it, my app was not usable (always stopped after a foreground). Tested on debug and release builds.
Also, this allows setting a `logFile` option from RN. Coupled with the new node state UI, this makes for a super useful way to understand what's actually happening when running on device. This wasn't possible before because they only way to get at the textile log file when running on device was to download the entire container (at least on iOS) and try to match dates when you did things... no good.
=> Fix node stopped state

android/app/build.gradle
If keystore env var isn’t set, just provide a string so dev compile can work
=> Fix Android dev mode compile

App/Components/ProgressiveImage.js
Just uses an opacity switch to show the full res only when finished loading successfully 
fixes #164
=> Removes mid-state which seemed to generate an extra image request

.circleci/config.yml, ios/fastlane/Fastfile, package.json, yarn.lock
This will archive all iOS build products (ipa and dsym) as well as generate and archive the JS source map.
The dsym and JS source map are zipped up and uploaded to AppCenter automatically.
=> ios build artifacts + upload

App/Components/ShareToThread.js, App/Containers/AddThreadScreen.js, App/Navigation/ShareToThreadNavigation.js, App/SB/components/BottomDrawerPhotos/index.js, App/SB/components/PhotoBoxEmpty/index.js, App/SB/views/PhotoDetail/index.js, App/Sagas/TextileSagas.ts
Tricky one because the share dialog is in a modal. That means that the thread creation needs to be able to live in that modal as well. Now now the modal displays a navigation stack that enables that behavior.
=> Put the thread creation into the share modal flow

ios/TextilePhotos.xcodeproj/project.pbxproj
The library wasn't working in iOS, just calling a function a an undefined object since the native module wasn't there. No big deal, just annoying error messages while developing.
=> Manually link the ios libs for react-native-permissions

package.json, yarn.lock
Some header search path settings in the react-native-fabric Xcode project were causing build problems for our project ("Argument list too long: recursive header expansion failed"). Basically doing the same thing as this PR on the original repo:
https://github.com/corymsmith/react-native-fabric/pull/169
=> Point at our fork of react-native-fabric

App/Redux/TextileNodeRedux.ts, App/Sagas/NodeLifecycle.ts, App/Sagas/TextileSagas.ts, App/Sagas/index.ts
Feeling good about the node start/stop logic. Seems solid and will always run the node in the background for 20 seconds, whether the background session results from a foreground > background transition or from launching into the background because of a location or background fetch trigger.
Need some help:
I want to clean up all the things we do after the node is started and/or comes online. I deleted a bunch of old code, code that did some of those important things. Go through it with me and let's identify all the things that need to happen and exactly when/how they should happen.
=> Node lifecycle, background triggers

App/Containers/App.tsx, App/Containers/ThreadsList.js, App/Redux/TextileNodeRedux.ts, App/Redux/ThreadsRedux.ts, App/SB/views/Settings/GetServiceInfo.js, App/SB/views/Settings/index.js, App/SB/views/ThreadsDetail/index.js, App/SB/views/UserProfile/index.js, App/Sagas/NodeCreated.ts, App/Sagas/NodeLifecycle.ts, App/Sagas/NodeOnline.ts, App/Sagas/NodeStarted.ts, App/Sagas/TextileSagas.ts, App/Sagas/index.ts, App/Services/EventHandlers/LocationEventHandler.ts
Feeling good about the node start/stop logic. Seems solid and will always run the node in the background for 20 seconds, whether the background session results from a foreground > background transition or from launching into the background because of a location or background fetch trigger.
Need some help:
I want to clean up all the things we do after the node is started and/or comes online. I deleted a bunch of old code, code that did some of those important things. Go through it with me and let's identify all the things that need to happen and exactly when/how they should happen.
Todo:
=> Node lifecycle, background triggers (2)

.circleci/config.yml, App/Containers/App.tsx, App/Containers/RootContainer.tsx, android/fastlane/Fastfile
Issue is we need access to the persisted preferences state to decide whether or not to start monitoring. That state wasn't available in `App.tsx` (too early, state not rehydrated from persistence yet). So for now, I moved the logic to `RootContainer` which isn't rendered until persistence is done initializing. Not the long term solution... I think we can do this as a saga real nice, just need a little more time to figure it out not on a Friday night.
=> Move location monitor

App/Sagas/NodeLifecycle.ts, App/Sagas/TextileSagas.ts, App/Sagas/ThreadsSagas.ts, App/Sagas/index.ts
Ok i think this is simple and works. Idea is to make sure the default thread exists right after stating the node, but before dispatching the `startNodeSuccess` action. Since we don't really run any code until after the node is started, it is then safe to assume the default thread exists everywhere else. Fixes #428
=> Make sure default thread is created before startNodeSuccess

ios/Mobile.framework/Headers, ios/Mobile.framework/Mobile, ios/Mobile.framework/Modules, ios/Mobile.framework/Resources, ios/TextilePhotos.xcodeproj/project.pbxproj, ios/fastlane/Fastfile, package.json, yarn.lock
- Bumps `go-mobile@0.1.7` which contains a releasable iOS framework built in CI.
- Re-includes symbols for iOS upload
=> Proper framework embed

package.json, yarn.lock
Yet another framework update.
- Adds a panic catch (that may or may not work, need to see) for this crash: https://fabric.io/we-are-set-inc/ios/apps/io.textile.wallet/issues/5b982b6d6007d59fcd61a83a?time=last-thirty-days
- Does not set services like `TextileService` to `nil` on `Stop()`... have a hunch this may be the root cause of a few of these crashes from trying to access de-allocated objects (`EXC_BAD_ACCESS KERN_INVALID_ADDRESS`)
=> bump go-mobile@0.1.9

App/Containers/ThreadsList.js
Removing that overlay in favor of the inline onboarding that we had.
=> removes tour overlay in Threads view

android/app/src/main/AndroidManifest.xml
I missed this from Android on first time around,
https://developer.android.com/training/app-links/verify-site-associations
it's a way to verify that our domain is owned by the same people who create the app (same as ios associated links verification). it means that instead of getting a list of viable apps to open the link in android it should open directly, which should help out android based invites a lot
=> Adds auto verify to android deeplinks

.circleci/config.yml, android/app/build.gradle, ios/TextilePhotos.xcodeproj/project.pbxproj
Generate and archive sourcemaps for iOS and Android builds. These can be used to get more information from JS stack traces.
=> Sourcemaps

App/Components/KeyboardResponsiveContainer.tsx, App/Containers/Comments.tsx, App/Containers/Styles/CommentsStyle.ts, App/SB/views/OnBoarding/index.js, App/SB/views/OnBoarding/statics/styles.js, App/SB/views/ThreadsEditFriends/index.js, App/SB/views/ThreadsEditFriends/statics/styles.js
Use `SafeAreaView` in a few key places so padding is correct at top and bottom of the screen on iPhone Xish models:
1. Onboarding
2. Comments
3. Invite peers
There is also a layout issue for iPhone X with the sign up/in screens as well, but something wasn't straight forward about fixing it, so I bailed since we'll be getting rid of those screens soon with profiles coming.
@andrewxhill also mentioned a crash that happens in the sim sometimes when navigating back from the comments screen. Something about `Unsupported layout animation createConfig property (null)`. I tinkered around and realized that might also be a real crash for people that use hardware/bluetooth keyboards. This PR fixes that crash.
=> iPhone X fixes

App/Sagas/NodeLifecycle.ts, typings/react-native-background-fetch/index.d.ts
Correctly model `react-native-background-fetch` constants to avoid JS crash in node lifecycle.
This should fix the problems we've been seeing with node lifecycle.
=> Node lifecycle fix

.gitignore, App/Sagas/NodeLifecycle.ts, ios/Textile.xcodeproj/project.pbxproj
1. Update .gitignore
2. Use `yield call()` to trigger background session and end it. Mostly just for consistency and sanity.
3. Update the signing settings for the `TextileTest` target. This allows adhoc builds from Xcode installed to your device to work without errors.
=> Couple tweaks

App/Redux/TextileNodeRedux.ts, App/Sagas/NodeLifecycle.ts, App/Sagas/index.ts
I'm about 85% confident in this change. Let's see how it works.
Should fix the problem of the double default thread because it should assure that the node creation and startup sequence can't only be called once at a time.
=> Better handling of node creation and start

ios/fastlane/Fastfile
Seemed cool, is cool, but requires that the CI build wait for App Store Connect processing of the binary to finish. Sometimes it's quick, but sometimes it takes an indefinite and long period of time. Either way, we'd have to pay for the CI time, so not worth it.
=> Don't submit for review from ci

.circleci/config.yml, .env.example, App/Sagas/DeepLinkSagas.ts, Gemfile.lock, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, fastlane/Fastfile, fastlane/Pluginfile, ios/Textile/Info.plist
Defaults to `textile-dev://`, updated in env specific builds on CircleCI. Schemes are as follows:
- production: `textile`
- beta: `textile-beta`
- dev: `textile-dev`
So, when you have an invite URL, you can choose with version of the app to open it with by editing the URL scheme accordingly.
Made an update where you can have a url with or without `www.` in it (important because our web page redirects to `www.textile.photos` then you may copy that url.
=> Parameterize url scheme

App/Containers/ThreadsManager.js, App/Containers/Wallet.js
couple preferences here, open for push back 
Nut instead of Gears, it's a little softer icon.
New thread is a list add, instead of a plus. Just feels tricky to have two plus signs for different actions in the header (other one being the add image in the stream screen)
=> Proposal for 2 icon changes

App/SB/components/RadioButton/index.js, App/SB/components/ThreadSelect/ThreadSelectCard.tsx
textile is great! i've honestly waiting for something like this to bubble up and am excited to see how usable it is even for not p2p heads like me :)
this PR fixes something i ran into when initially poking around in the app, where tapping on the radio button in the "Thread select" view for an image wouldn't select the corresponding thread. hopefully uncontroversial, but let me know if there's anything i should do differently
=> making the radio button a touch target for the thread select screen

App/Containers/MailListSignupScreen.tsx, App/Containers/OnboardingScreen/index.tsx
This bug where the email form submission wasn't working the first try, but would then work if you re-started the app, is a strange one. I was able to reproduce it for a while, but with a meaningless "network request failed" error. And then out of nowhere, it just started working and I can no longer reproduce it. This PR does the next best thing for now and catches the error, displays a toast with the error message, and allows the user to retry the submission. Let's see if that works.
UPDATE: Snuck in a commit to fix the arrow positioning during onboarding on iPhone X screens.
Fixes #735 
Fixes #737
=> Handle error from mail list sign up, allow retry

App/Sagas/Migration.ts
This wasn't stopping the peer id migration from working (the missing env item on the ci server was), but this was causing a confusing error.
=> Don't announce peer until we have all the needed data

App/Components/InviteContactModal.tsx, App/Services/EventHandlers/TextileNodeEventHandler.ts, App/Services/Notifications.ts, App/Services/__tests__/__snapshots__/Notifications.ts.snap
@sanderpick I think it now makes sense only to call .contacts() for a refresh in two cases,
1. Node startup.
2. JOIN block event
so i remove other cases of it happening. let me know if you see other reasons to do it
=> Particularly handy to have while we are testing

App/Containers/PhotoScreen.tsx, App/SB/components/ThreadDetailCard/index.tsx, App/Sagas/NotificationsSagas.ts
Saw this again and just wanted to nip it.
Makes more sense, when you click a comment you want to see what the commented as well as what they commented on. 
Based it of @asutula's suggestion, just link into the PhotoScreen but don't limit the comment count.
=> Clicking comment now goes to Photo Screen

App/Components/NodeLogsScreen.tsx, App/Navigation/AppNavigation/Primary/index.ts, App/SB/views/UserProfile/index.js, App/Sagas/NodeLifecycle.ts, App/Themes/Constants.ts
Get's pretty brutal on memory usage to read in the whole log (can be many MB), so reading in the last 300KB for now. Provides refresh and copy to clipboard. Let's see how that feels.
=> Node logs screen

App/Components/Avatar.tsx, android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
- Adds a `View` wrapper to `TextileImage` the includes the border radius, `overflow: hidden` is also needed
- Updates android gradle plugin to latest (3.3.0), which requires gradle 4.10.1
fixes #837
=> Android: avatar border radius fix

App/Redux/AccountRedux.ts, App/Redux/AccountSelectors.ts, App/Sagas/Account/AccountSagas.ts, App/Sagas/NodeLifecycle.ts, App/Sagas/UploadFile.ts, package.json, yarn.lock
There were a couple issues here:
- `exp` is not a string, it's a proto Timestamp object
- the results from the framework's get / list / refresh session methods can now return an empty byte slice, so the TS api needs to return undefined in that case
=> Fix proto CafeSession handling

App/screens/group/group.tsx
You get the crash if you try to render 0 length text in a `Text` component. If you effectively do this:
```
<Text>{''}</Text>
```
the UI will crash.
=> Feed UI crash fix

App/Components/QRCodeModal.tsx, App/Components/photo.tsx, App/Containers/OnboardingScreen/index.tsx, android/app/src/main/AndroidManifest.xml
seemed to loose the scheme entries
also, chrome on latest android seem to steal the deeplinks from camera, but the links from browser work fine. so just defaulting to link. can't control ios user showing qr to and android scanner, so needs to just go to https that all can use. then in browser you'll get the deep link by clicking 'accept' button
=> Deep link fix on android

App/Redux/NotificationsRedux.ts, App/Services/EventHandlers/NotificationEventHandler.ts
Bypass the notification lookup stuff if the userinfo payload (just containing the internal notification object) exists
=> Click to content from local notifications in Android

App/Components/ProgressiveImage.tsx
currently the app goes from super low res thumb to full size image. this now uses all three options, thumb => small => full when displaying an image, helping to remove the grainy thumb asap
fixes https://github.com/textileio/textile-mobile/issues/1005
=> Full use of image size options

App/Components/ProcessingThread.tsx, App/Redux/ThreadsRedux.ts, App/Redux/__tests__/ThreadsRedux.ts, App/Sagas/ThreadsSagas.ts
Couple things I saw playing more with it.
- Remembers threadName on a retry request
- If progress was dismissed and then user tries to accept the invite again, it will undismiss the progress so they have some feedback
=> More enhancements to the join retry flow

App/Components/like-and-comment.tsx, App/Containers/PhotoScreen.tsx, App/screens/group/group.tsx
Fixes #1082. Display the comments count next to the likes count beneath photos in groups.
=> Display Comments Count Next to Likes Count

App/features/photos/actions.ts, App/features/photos/models.ts, App/features/photos/reducer.ts, App/features/photos/sagas.ts, App/features/photos/selectors.ts, App/screens/photos.tsx
We want some control over how concurrency is used to process camera roll photos, adding them to the local Textile node. This allows us to balance speed and memory consumption. 
Closes #1073
=> Process photos using a queue and workers

App/Components/Loading.tsx, App/Containers/App.tsx, App/Containers/StatusCheck.tsx
We were previously not instructing redux-persist to display any view while loading the persisted data. This PR tells redux-persist to display our `Loading` component with a red spinner while it's loading the persisted data.
I also updates the `StatusCheck` screen (which blocks any UI from rendering until the node is started) to display a blue spinner.
The idea is we can know, while the spinners are displaying during app startup, which is taking a long time.
=> Display loading component while loading persisted data

ios/Textile/Info.plist, ios/fastlane/Fastfile
Decision was to make file sharing enabled by default so that all dev and beta builds have it, but then to disable it during the release build.
Should make it easier to grab repo data for any dev or beta build.
=> File sharing to iTunes

ios/fastlane/Fastfile
At one point with older RN we needed to disable the new build system, but hopefully that's fixed now. Hoping this helps with these random CI failures that happen too often
=> Try allowing default build system

yarn.lock
Pulled the latest master and ran a `yarn install` which resulted in these updates to `yarn.lock`. I'm assuming that the recent PR from @balupton didn't include the update because he probably used `npm` locally.
=> Update yarn.lock for current package.json

App/Sagas/TextileSagas.ts, App/Sagas/index.ts, App/Services/CameraRoll.ts, App/features/photos/sagas.ts
There was a case where the app doesn't have permissions to access camera roll by the time you toggle on camera roll auto pin. This makes sure you're prompted for permission when toggling on auto pin if you haven't been previously. Also did a little DRY refactor for the actual permission triggering code since it's used from other places as well.
=> Trigger permissions when toggling on auto pin

App/Components/NodeLogsScreen.tsx, App/Sagas/TextileEventsSagas.ts, App/Sagas/TextileSagas.ts, App/Sagas/index.ts, App/features/account/sagas.ts
**IMPORTANT:** This will require a delete and reinstall of the Beta app to allow the node logs to work again (they previously weren't being written to disk, and the only time that is configured is during node initialization which only happens one time, the first time the app runs).
* Write textile logs to disk
* Fix bug that would have prevented log file from being found
* Increases the log level to `DEBUG` when verbose UI is on, `ERROR` level otherwise
Fixes #1119
=> Fix node logs + extras

App/Redux/configureStore.ts, App/Sagas/index.ts
This was definitely causing a bug where the node was being started with a log level of `ERROR` even if the user has verbose UI on and it was supposed to be `DEBUG`. This is because we were reading the verbose UI redux state before the persisted preference data was merged into the state. The default value for verbose UI (before re-hydration) is `false`, therefore log level was set to `ERROR`.
This doesn't let any sagas run until re-hydration is complete.
I'm trying to think through other potential bugs this could have been causing, hard to say, but it could have definitely be causing some weirdness related to issues @andrewxhill has been seeing.
=> Block root saga until redux is rehydrated

.circleci/config.yml
The CircleCI Xcode 10.2.1 image is missing some package (probably `watchman`) so building for distribution breaks because the js bundle isn't created.
=> xcode 10.2.0 for release

App/Components/NodeLogsScreen.tsx
scrollview approach works well on iOS so i didn't want to remove it. at the same time, it doesn't work on android because of reason linked here, https://github.com/textileio/photos/issues/1136. so for android it uses a flatlist and allows row-based copy by touch.
=> uses a flatlist instead of scrollview-textarea for android log

App/Containers/PhotoScreen.tsx, App/Redux/UIRedux.ts, App/Sagas/index.ts
Fixes #1143. Fixes #1159. The actions dispatched from `PhotoScreen.tsx` and watched for in the saga needed to be brought in line with the new `createAsyncAction` structure.
=> Fix asynchronous likes

App/Navigation/AppNavigation/Modal/Settings/index.ts, App/SB/views/UserProfile/index.tsx, App/features/group/file-sync/models.ts, App/features/group/file-sync/reducer.ts, App/features/group/file-sync/selectors.ts, App/screens/file-sync.tsx, package.json
Lets us monitor file sync in verbose ui mode. Any errors are displayable by tapping the alert icon. Once something is in a error state, that is the end of the road for that item (for now anyway), so you can clear it from the redux state by tapping the 'x' icon.
=> File sync group status screen

App/Components/CreateThreadModal.tsx
This is a quick fix for #1240. This issue was caused by a flag in the modal's state, `submitted`, which disables the new thread functionality. It is set to `true` the first time a new thread is created, and then never reset, causing the modal to silently fail. But really, I think we should address these issues:
- Should this really be a modal? Since several other screens need to navigate to this page, and it is pretty complex, I think it might make sense to refactor it into its own navigable screen. That would simplify solving some of the problems below.
- Most of the redux state uses an indexed type for pending requests (like adding or removing a contact, ignoring a block, etc.) so that multiple requests can be theoretically handled at once. It appears that the new thread functionality …
=> Fix inability to resubmit create new thread modal

.circleci/config.yml
using an xl instance was mainly to eliminate the possibility of machine memory being a problem. I don't think that was the issue, so putting it back to large again.
=> put it back to large ci machine

package.json, yarn.lock
It respects the versions specified by the containing android project
=> use our fork or react-native-keyboard-input

App/Components/comments.tsx
related to https://github.com/textileio/photos/issues/1228
Just adds a small indent and connecting line to photo comments so you can easily distinguish them from in-line group messages
=> Adds visual hierarchy to comments versus in-line group messages

App/Components/ListItem.tsx, App/Components/join.tsx, App/Redux/ThreadsRedux.ts, App/SB/components/ContactSelect/index.tsx, App/SB/views/ThreadsEditFriends/index.tsx, App/SB/views/ThreadsEditFriends/statics/styles.js, App/Sagas/ThreadsSagas.ts
While playing with multipeer I realized that we already solve the first use case, invite nearby. It's part of the native share in ios anyway. So realized that a small UI tweak could just make it more obvious for now.
Previously,
Now,
Adds an explicit method for Nearby in iOS. Also makes copy it's own button instead of hidden in the native share. Finally, it reuses the List element from the Contacts screens for a bit of consistency.
=> cleans up the invite flow, makes more obvious methods

App/Sagas/DeepLinkSagas.ts
fixes https://github.com/textileio/photos/issues/1256
^ not final text. 
This is for deeplink only and schema only support. It is in the form of,
`textile://www.textile.photos/invites/cafe#token=<cafe-token>&peerId=<cafe-peerId>&url=<cafe-url>`
=> adds a deeplink routes for direct cafe invites

App/Components/Avatar.tsx
a couple months back we had an avatar caching issue. my best guess of what was happening was that the cafes sent a 200s response that was actually an error (e.g. an html response). it led to some avatars turning grey and never recovering. they didn’t recover because that bunk response was cached in RN via a flag in the avatar image `cache='force-cache'`. 
to fix that issue we simply changed it back to, `cache='reload'` which flushed the bad results and everything worked again. Except that now the avatars do this little flash most times you load the screen. 
To fix this, I'm going to put the flag back to `force-cache`. However, to avoid any issues like we hit last time, I'm going to just wrap an un-cached image with a cached one... The one in the background will be force-cache and the one …
=> back to caching avatars

App/Redux/RootReducer.ts
Migrates `onboarded` value and sets a sensible value for `initialized` to `true` (thinking that if you're migrating, you've previously installed and initialized the node).
=> Migration fix
