- App/Containers/TextilePhotos.js
- App/Redux/TextileRedux.js
- App/Sagas/TextileSagas.js
- App/Sagas/index.js
- App/Services/PhotosTask.js
- index.js
- ios/NativeModules/UploadTask.m
This should make the errors appear in our redux logger. Also cleaned up redux to get rid of unused code.
> Image upload error redux

- App/Containers/TextilePhotos.js
- App/Redux/TextileRedux.js
- App/Sagas/TextileSagas.js
Noticed the image upload progress was broken, here's the fix
> Fix bug where image wasn’t being updated with upload progress

- android/app/src/main/java/com/textilephotos/textileipfs/TextileIPFSModule.java
- ios/Mobile.framework/Versions/A/Headers/Mobile.h
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/Mobile.framework/Versions/A/Headers/Net.objc.h
- ios/Mobile.framework/Versions/A/Modules/module.modulemap
- ios/NativeModules/TextileIPFS.m
> Updates framework

- App/Containers/TextilePhotos.js
- App/Redux/EventLogging.js
- App/Redux/IpfsNodeRedux.js
- App/Sagas/StartupSagas.js
- App/Sagas/TextileSagas.js
- App/Sagas/index.js
- TextileIPFSNativeModule.js
- android/app/src/main/java/com/textilephotos/textileipfs/TextileIPFSModule.java
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/NativeModules/TextileIPFS.m
> Removes manual gateway start starts gateway in node

- TextileIPFSNativeModule.js
- android/app/src/main/java/com/textilephotos/textileipfs/TextileIPFSModule.java
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/NativeModules/TextileIPFS.m
> Adds gateway password methods in bridge

- App/Components/PhotoGrid.js
- App/Containers/PhotoViewerScreen.js
- App/Containers/RootContainer.js
- App/Containers/TextileManager.js
- App/Containers/TextilePhotos.js
- App/Navigation/PhotosNavigation.js
- App/Navigation/Styles/NavigationStyles.js
- App/Sagas/TextileSagas.js
- TextileIPFSNativeModule.js
- android/app/src/main/java/com/textilephotos/textileipfs/TextileIPFSModule.java
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/NativeModules/TextileIPFS.m
> New jwt etc

- App/Sagas/TextileSagas.js
- App/Sagas/index.js
- TextileIPFSNativeModule.js
- ios/Mobile.framework/Versions/A/Headers/Mobile.h
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/Mobile.framework/Versions/A/Headers/Net.objc.h
- ios/Mobile.framework/Versions/A/Modules/module.modulemap
The issue here was that after a backgrounding, the node would go offline for some reason. This is only seen in a release build... everything is fine when debugging.
Took me awhile to get this right... back and forth between here and go layer. Basically, we just need to stop the node when it goes to `inactive` state. https://github.com/textileio/textile-go/pull/87 lets the node cleanly restart.
> Stop node on inactive state, clean restart, update frameworks

- App/Redux/EventLogging.js
- App/Redux/IpfsNodeRedux.js
- App/Redux/TextileRedux.js
- App/Sagas/StartupSagas.js
- App/Sagas/TextileSagas.js
- App/Sagas/index.js
Update to Mobile.framework that starts up faster
Clean up sagas
Block UI until node is started
> Various improvements

- App/Containers/LoginScreen.js
- App/Redux/AuthRedux.js
not sure you guys noticed, but was annoying. this fixes
> fixes error bouncing instead of dismissing

- android/app/src/main/AndroidManifest.xml
> forces orientation to remain in portrait mode when app is open

- App/Containers/PhotoViewerScreen.js
makes android full res much mo responsive. suuper simple update.
> simply removes flatlist props... 

- App/Components/AsyncImage.js
Kept seeing this warning and wanted to nip it
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in AsyncImage (at PhotoViewerScreen.js:33)
in RCTView (at View.js:60)
in View (at index.js:138)
in RCTView (at View.js:60)
in View (at index.js:133)
in ViewTransformer (at index.js:178)
in TransformableImage (created by CellRenderer)
in RCTView (at View.js:60)
in View (at VirtualizedList.js:1664)
in CellRenderer (at VirtualizedList.js:670)
```
> Cancel any async requests 

- App/Components/AsyncImage.js
- ios/TextilePhotos/Info.plist
Noticed the app icon said Textile Photos, which is too long. reduced it here.
also realized if we are going to store `this.request` we might as well just store `this.hascancled` instead, much simpler than nested promises until this is moved to a full redux way.
> just 'Textile' on the app icon

- App/Containers/PhotoViewerScreen.js
okay, this fixes #91 for now, that whole flow will change so i didn't spend any time over thinking it
little bit more pop in avatar, rearranges things in places
> just a quick fix to make caption not look so bad

- App/Config/ReactotronConfig.js
Thanks to https://github.com/infinitered/reactotron/issues/272, fixes #99.
> Enables reactotron when running debug on actual device

- App/Containers/TextileManager.js
- App/Redux/TextileRedux.js
Fix bug causing image upload errors to not display, deal with cancelled upload state.
> Fix image upload errors

- App/Containers/TextilePhotos.js
- App/Redux/IpfsNodeRedux.js
Quickie just so you're not staring at 'undefined' node status with no information as to what went wrong
> Display node error

- ios/Mobile.framework/Versions/A/Headers/Mobile.h
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/Mobile.framework/Versions/A/Headers/Net.objc.h
- ios/Mobile.framework/Versions/A/Modules/module.modulemap
goes with https://github.com/textileio/textile-go/pull/129
> new frameworks with small change for pinging threads

- App/Navigation/OnboardingNavigation.js
- App/Redux/EventLogging.js
- App/Redux/TextileRedux.js
- App/Sagas/TextileSagas.js
- App/Services/PhotoUtils.js
- ios/TextilePhotos/Info.plist
> Uri based cameraroll tracking

- App/Containers/LoginScreen.js
This layout issue breaks the UI guideline for iPhone X.
I just wrapped the whole screen in a SafeAreaView.
B.T.W. How can I get a referral code?
> Fix layout of LoginScreen for iPhone X.

- App/Config/ReduxPersist.js
- App/Redux/TextileRedux.js
- App/Sagas/TextileSagas.js
fixes #146 
this feels a lot better
> Photo processing with state

- App/Sagas/TextileSagas.js
- App/Services/PhotoUtils.js
> Full camera roll ignore list on first load

- App/Containers/TextilePhotos.js
- App/Containers/Threads.js
- App/Sagas/TextileSagas.ts
fixes https://github.com/textileio/textile-mobile/issues/202
fixes https://github.com/textileio/textile-mobile/issues/196
> Fixing thread mismatch stuff

- App/Containers/TextilePhotos.js
- App/Redux/TextileNodeRedux.ts
- App/Sagas/TextileSagas.ts
> Fixed undefined state on first run

- App/Containers/LoginScreen.js
- App/Containers/TextileManager.js
- App/Containers/TextilePhotos.js
- App/Redux/AuthRedux.ts
- App/Redux/ThreadsRedux.ts
- App/Sagas/TextileSagas.ts
- App/Sagas/index.ts
- App/Services/DeepLink.js
fixes https://github.com/textileio/textile-mobile/issues/206
> Stores deeplink in threads to be processed post-login

- App/Redux/PreferencesRedux.ts
- App/Redux/TextileNodeRedux.ts
- App/Redux/__tests__/PreferencesRedux.ts
- App/Sagas/TextileSagas.ts
- TextileNode.ts
- android/app/src/main/java/com/textile/textilenode/TextileNode.java
- ios/NativeModules/TextileNode.m
Oops committed this to the branch from the previous PR, just going to re-use it.
Closes #190
> Save mnemonic for later

- App/Containers/ThreadInvite.js
- App/Containers/Threads.js
- App/Redux/ThreadsRedux.ts
Didn't get fancy here since we'll pave over it all soon enough. But will be helpful for debugging i think.
> Allow thread retries

- ios/TextilePhotos.xcodeproj/project.pbxproj
- ios/TextilePhotos/AppDelegate.m
Let's see if we get that email from Apple on this build
> Remove all traces of notification libs

- App/Components/Styles/PhotoGridStyles.js
- App/SB/components/PhotoWithTextBox/index.js
- App/SB/components/PhotoWithTextBox/statics/styles.js
- App/SB/views/PhotoDetail/index.js
- App/SB/views/ThreadPhotoDetail/index.js
> Better image sizing

- App/Services/PhotoUtils.js
- android/app/build.gradle
- android/app/src/main/java/com/textile/MainApplication.java
- android/settings.gradle
- ios/TextilePhotos.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Removes react-native-image-resizer
> Module cleanup

- App/Containers/TextileManager.js
- ios/TextilePhotos.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Also disable location monitoring for now.
> Remove react-native-permissions

- App/Redux/PreferencesRedux.ts
- App/Sagas/TextileSagas.ts
Was causing all sorts of problems, including how we saw sign in not working.
> Fix release mode JS exception

- App/Config/ReduxPersist.ts
this param would be missing, could cause issues if not handled nicely by redux?
> cameraroll migration

- App/Components/Avatar.js
- App/Components/Styles/AvatarStyles.js
- App/Containers/TextilePhotos.js
- App/Containers/Threads.js
- App/Navigation/Styles/NavigationStyles.js
- App/SB/components/CommentCard/index.js
- App/SB/components/FeedItem/statics/styles.js
- App/SB/components/SmallIconTag/index.js
- App/SB/components/SmallIconTag/statics/styles.js
- App/SB/components/ThreadDetailCard/index.js
- App/SB/components/ThreadDetailCard/statics/styles.js
- App/SB/views/Settings/index.js
- App/SB/views/Settings/statics/styles.js
- App/SB/views/ThreadsDetail/index.js
- App/SB/views/ThreadsDetail/statics/styles.js
- App/SB/views/UserProfile/index.js
- App/SB/views/UserProfile/statics/styles.js
- ios/Mobile.framework/Versions/A/Headers/Mobile.h
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/Mobile.framework/Versions/A/Modules/module.modulemap
Fixes #328 
Fixes #330 
Fixes #331 
Fixes #326 
Fixes #327 
Fixes #329 
updates frameworks
> Cleanups ui

- App/Containers/ThreadsList.js
- App/Redux/TextileNodeRedux.ts
- App/Redux/UIRedux.ts
- App/SB/components/CommentCard/index.js
- App/SB/components/ThreadDetailCard/index.js
- App/SB/views/PhotoDetail/index.js
- App/SB/views/ThreadsDetail/index.js
- App/Sagas/TextileSagas.ts
- App/Sagas/index.ts
- ios/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- Metadata is now only requested when needed -- when photo sizes are required mostly
- refreshMessages is now called whenever user pull refreshes the ThreadsList or ThreadsDetail scrollviews and before either of those threads are rendered
refreshMessages should be called sometimes during the background routines, but not certain where that fits in.
> Frameworks 228 update

- App/Navigation/AppNavigation/Primary/TabNavigator/index.tsx
> Changes default tab on app start to threads

- App/Components/Avatar.js
- App/SB/views/UserOnBoarding/Step2.js
- App/SB/views/UserOnBoarding/statics/styles.js
Huge PR here, take your time going through it.
> Round avatar

- .env
- .env.staging
Production values have been updated on the CI server
> Updated .env files

- App/Redux/PreferencesRedux.ts
Did a little experiment just to see how this works. Might as well use it. Pretty cool actually.
> Make tour screen and service keys typesafe

- App/SB/components/BottomDrawerPhotos/index.js
- App/SB/components/FeedItem/statics/styles.js
- App/SB/components/ThreadDetailCard/index.js
- App/SB/components/ThreadDetailCard/statics/styles.js
- App/SB/views/Settings/GetServiceInfo.js
- App/SB/views/ThreadsDetail/index.js
- TextileNode.ts
just show the count of likes on a photo (skipping usernames for the moment until we aren't doing a bunch of fetches)
uses 'medium' resolution in the threads detail view, noticed it was on 'small' which was pretty grainy
> Likes and resolution

- App/Sagas/NodeStarted.ts
Fix problem where user reported endless spinner on signup.
> Catch onNodeStarted errors

- App/Components/Avatar.js
- App/SB/components/ThreadDetailCard/index.js
- App/SB/views/PhotoDetail/index.js
> Loads small image before pulling medium

- App/Components/PhotoGrid.js
- App/Components/ProcessingImage.tsx
> Fixes that cancel button hanger

- App/Containers/RootContainer.tsx
- App/Containers/Styles/RootContainerStyles.js
- App/Containers/Styles/TextilePhotosStyle.js
- App/Containers/Wallet.js
- App/Redux/PreferencesRedux.ts
- App/Sagas/NodeLifecycle.ts
- Possibly fixed a bug that would cause the node to sometimes not start.
- Display notifications about what's going on with the node in the background if `verboseUi` is `true`
- Display app/node state message in `RootContainer` so it's visible no matter which screen you're on
Fixes #467 I hope
> Investigate node cycle

- App/Sagas/NodeLifecycle.ts
Query for `verboseUi` preference each time we might display a notification. This avoids the notifications still displaying for the remainder of the node start/stop cycle after you toggled `verboseUi` off.
Added a little delay after the node is stopped, before the background task ends, to hopefully allow the 'node stopped' notification to reliably display.
> Node notification tweaks

- App/Redux/AuthRedux.ts
- App/Redux/CameraRollRedux.ts
- App/Redux/ContactsRedux.ts
- App/Redux/DevicesRedux.ts
- App/Redux/NotificationsRedux.ts
- App/Redux/PhotoViewingRedux.ts
- App/Redux/PhotoViewingSelectors.ts
- App/Redux/PreferencesRedux.ts
- App/Redux/ProcessingImagesRedux.ts
- App/Redux/StartupRedux.ts
- App/Redux/TextileNodeRedux.ts
- App/Redux/ThreadsRedux.ts
- App/Redux/UIRedux.ts
- App/Redux/UploadingImagesRedux.ts
- App/Redux/__tests__/NotificationsRedux.ts
- App/Redux/__tests__/ThreadsRedux.ts
- App/Redux/__tests__/UIRedux.ts
- App/Redux/__tests__/UploadingImagesRedux.ts
- App/Redux/configureStore.ts
- tslint.json
Wanted to try this out, let's keep it.
> Tslint fixes for Redux dir

- App/Services/DeepLink.ts
- android/app/build.gradle
- ios/TextilePhotos/Info.plist
Fix some logic that got lost last week. All deep links were broken, this is the fix.
> Fix Deep Link Parsing

- package.json
- yarn.lock
Updates go-mobile with a fix for https://github.com/textileio/textile-go/issues/283
> bump go-mobile@0.1.8

- .circleci/config.yml
- README.md
- android/app/build.gradle
- ios/TextilePhotos/Info.plist
We _do_ still have lint/tests in master build. So make them a pre-req for the deploy still. Doh
Hopefully fixes the badge on readme
> require lint/tests before andriod/ios deploy. try to fix badge

- App/SB/views/UserProfile/index.js
- TERMS.md
> Adds terms to the main settings page

- App/Components/Avatar.tsx
- App/Components/KeyValueText.tsx
- App/Models/TextileTypes.ts
- App/SB/components/ThreadDetailCard/index.tsx
- App/SB/components/ThreadDetailCard/statics/styles.js
- App/SB/views/ThreadDetail/index.js
Closes #497 
Closes #509 
Displays up to two recent comments in the thread image, limited to one line each. Also displays "See all N comments...".
> Comments in thread

- App/Models/TextileTypes.ts
- App/Redux/NotificationsRedux.ts
- App/Sagas/NodeLifecycle.ts
- App/Sagas/NotificationsSagas.ts
- App/Services/EventHandlers/NotificationEventHandler.ts
- App/Services/Notifications.ts
- package.json
- yarn.lock
I'll look at the broken notifications tomorrow, but just saw this little cleanup possible
> Little cleanup of notification type

- App/Containers/PhotoScreen.tsx
- App/Navigation/AppNavigation/Primary/index.ts
- App/SB/components/ThreadDetailCard/index.tsx
- App/SB/views/ThreadDetail/index.js
- App/Sagas/NotificationsSagas.ts
Wired up to notifications screen.
G2G @channel
Fixes #510
> Single photo screen

- App/Containers/Wallet.js
still uses overlay for now but didn't point to the new style file
> fixes styles

- App/Sagas/NodeLifecycle.ts
Maybe this will help @andrewxhill's phone not get suspended before we can process the transition to background.
> Start background task early in the foreground

- App/Sagas/NodeLifecycle.ts
Kinda a shot in the dark, but lets see what happens. 'Inactive' happens on the way to 'background', so a little earlier in time.
One side effect of this is the verboseUI notif that previously displayed 'running node in background for 20 seconds' will no longer display because it's getting fired upon 'inactive' state. I guess apps in 'inactive' state can't display local notifs. This is similar to the behavior in foreground state.
> Trigger background state using inactive app state

- App/Sagas/NodeLifecycle.ts
Ok this one uses the fact that we can safely call create and start on the node even if is is already created and/or started. It's more of a brute force approach where we call create and start on the node for every background or foreground event we get no matter what. Additionally, if the event is a background event, we do our background task thing and let the node run for 20 seconds, but that can get interrupted by another foreground event.
@andrewxhill let's see how this works on that old phone of yours.
> Brute force approach

- App/Sagas/DeepLinkSagas.ts
- App/Services/EventHandlers/DeepLinkEventHandler.ts
- ios/TextilePhotos/AppDelegate.m
- ios/TextilePhotos/Info.plist
need to work on how to register the as deeplinks, they don't seem to come into the app quite the same. but i'll do that later. wanted to get it started.
> adds textile:// scheme to ios

- android/app/src/main/AndroidManifest.xml
turned out to be a simple fix to get those going. minus the overhead of spinning up android ha
> fixes sure-thing-link in android

- .circleci/config.yml
- ios/TextilePhotos.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> Xcode 10 Support

- App/Config/ReduxPersist.ts
- App/Redux/PreferencesRedux.ts
- App/Redux/__tests__/__snapshots__/PreferencesRedux.ts.snap
- App/SB/views/ThreadDetail/index.js
realized we never ask people to enable it, so unless they are going into notification settings and finding it, they probably aren't trying it out. 
looking at the verbose ui, it definitely helps
> adds a background location prompt after some usage

- App/SB/views/ThreadInvite/index.js
- App/Sagas/NodeLifecycle.ts
- App/Sagas/NodeOnline.ts
- App/Sagas/TextileSagas.ts
fixes the 'wait' instead of 'connect' on success (introduced that the other day by mistake)
also adds a couple more interesting logged lines for verboseui
> Fixes where it says wait

- ios/Textile.xcodeproj/project.pbxproj
Fix to get the iOS release build working
> Disable bitcode

- App/Sagas/NotificationsSagas.ts
catching the error here and logging it in case for some reason we're missing something
> Notification error

- android/app/src/main/java/com/textile/textilenode/TextileNode.java
The calls to the Android TextileNode native module were running on the UI thread. This makes sure all the interactions to the node api happen on a worker thread. Big improvement to UI smoothness. Fixes #571
> Interact with TextileNode on a worker thread

- App/Services/EventHandlers/TextileNodeEventHandler.ts
Fixes problem where thumbs weren't displaying for notifications showing in real time
> Transform real time notifs to typed versions

- App/Components/HeaderButtons.tsx
- App/Containers/Wallet.js
> Header button color prop support

- App/Components/CreateThreadModal.tsx
- App/Components/Styles/ThreadCreateModal.tsx
fixes https://github.com/textileio/textile-mobile/issues/678
> Avoid keyboard

- App/Components/PhotoStream.tsx
- App/Components/Styles/PhotoStreamStyles.tsx
- App/Containers/ThreadsList.js
- App/SB/views/ThreadDetail/index.js
multiple comments lately about not being easy to find how to add peers
> Adds helper button when thread is empty

- App/Components/QRCodeModal.tsx
Nothing fancy here, just a wording nit.
> Minor change 'Cancel -> Close'

- App/NativeModules/ScreenControl.ts
- android/app/src/main/java/com/textile/textilenode/ScreenControl.java
- android/app/src/main/java/com/textile/textilenode/TextileNodePackage.java
- ios/NativeModules/ScreenControl.h
- ios/NativeModules/ScreenControl.m
- ios/Textile.xcodeproj/project.pbxproj
> Native module to control screen sleeping

- App/Components/InvitePeerModal.tsx
- App/Components/Styles/InvitePeerModalStyles.tsx
- App/Containers/AddCaptionScreen.tsx
- App/SB/components/ThreadSelect/index.tsx
- App/SB/components/ThreadSelect/statics/styles.tsx
- App/SB/views/ThreadCreate/statics/styles.js
- App/SB/views/ThreadsEditFriends/index.js
carson, this could use a look on android when you have some minutes
> modals tested on large and small ios screens

- App/NativeModules/Textile/Api.ts
- App/NativeModules/Textile/__tests__/Api.ts
- App/Redux/PhotoViewingSelectors.ts
- App/SB/components/ThreadDetailCard/index.tsx
- App/SB/views/PhotoDetail/index.js
- App/SB/views/ThreadPhotoDetail/index.tsx
- App/Sagas/ImageSharingSagas.ts
- App/Sagas/NodeLifecycle.ts
- App/Sagas/PhotoViewingSagas.ts
- android/app/src/main/java/com/textile/textilenode/TextileNode.java
- ios/NativeModules/TextileNode.m
- package.json
- yarn.lock
Looks to be working. Some changes are in the "good enough for now" category. Created issues to track those potential improvements.
> Update to rc17

- App/Components/WalletHeader.tsx
- App/Redux/PreferencesRedux.ts
- App/Redux/__tests__/__snapshots__/PreferencesRedux.ts.snap
fixes #702 
worth testing on android @carsonfarmer because it relies on window dimensions which sometimes aren't perfect over there
but probably don't need to delay for that i don't think
> allow un to wrap on wallet screen when long

- App/Components/WalletHeader.tsx
- App/Redux/PhotoViewingRedux.ts
- App/Redux/PreferencesRedux.ts
- App/Redux/__tests__/__snapshots__/PreferencesRedux.ts.snap
- App/Sagas/NodeLifecycle.ts
- android/app/src/main/java/com/textile/textilenode/TextileNode.java
> Android add thread files

- App/Components/CreateThreadModal.tsx
- App/Components/QRCodeModal.tsx
- App/Components/ReferralCode.tsx
- App/Components/Styles/ThreadCreateModal.tsx
- App/Components/WaitListSignupScreen.tsx
- App/Containers/MailListSignupScreen.tsx
- App/Containers/OnboardingUsername.tsx
@carsonfarmer the fixes you added didn't do it for me on the sim or on my device. This seems to do the trick, though.
> Setting the height of inputs properly + create group modal fix

- App/Containers/OnboardingUsername.tsx
- App/Containers/ThreadsList.js
> Couple of fixes here

- App/Components/Avatar.tsx
> Local avatar when node started

- App/Config/ReduxPersist.ts
> Resets selected tab to groups on next migration

- App/Config/ReduxPersist.ts
thought i had already fixed this... but here's proof i hadn't
> geo flag to false

- App/SB/components/ContactSelect/index.js
There had to be one... JS file of course.
> avatar: missed update in ContactSelect component

- App/Redux/AccountSelectors.ts
- App/Sagas/NodeLifecycle.ts
- App/Sagas/UploadFile.ts
- package.json
- tests/__mocks__/TextileNode.ts
- yarn.lock
> sdk: bump to 1.0.19

- App/Containers/OnboardingScreen/index.tsx
Latest attempt to simplify the flow and fix this https://github.com/textileio/textile-mobile/issues/893
but haven't been able to recreate
> remove scroll finish callback

- App/SB/views/UserProfile/index.js
- App/Sagas/Account/AccountSagas.ts
- App/Sagas/Account/index.ts
- App/Sagas/Contacts/ContactsSagas.ts
- App/Sagas/ImageSharingSagas.ts
- App/Sagas/Migration.ts
- App/Sagas/NotificationsSagas.ts
- App/Sagas/PhotoViewingSagas.ts
- App/Sagas/TextileEventsSagas.ts
- App/Sagas/TextileSagas.ts
- App/Sagas/ThreadsSagas.ts
- App/Sagas/index.ts
- package.json
- yarn.lock
looks big, but all functions that used to be under Textile.api.funcName became Textile.funcName so touched a lot of files.
> updates to rc8

- App/Components/ReferralCode.tsx
- App/Containers/OnboardingScreen/index.tsx
- App/Sagas/DeepLinkSagas.ts
- android/build.gradle
The approach here was to clean up and simplify:
- Remove band aid fixes that haven't worked
- Remove array splicing based on redux state, always show referral code screen, pre-populated with a referral code when applicable
- Remove a couple things that might have been causing bugs
> Simplify onboarding code, remove possible bugs

- package.json
- yarn.lock
> 1.1.0 rc45

- App/Containers/OnboardingScreen/index.tsx
- android/app/src/main/AndroidManifest.xml
- package.json
- yarn.lock
felt redic that this bug has been live so long, let's get this out to android first thing in the a.m.
> Fix android onboarding

- App/Components/photo.tsx
- App/Containers/OnboardingScreen/index.tsx
still square images but at least the ui is visible
> fix android image overflow

- .circleci/config.yml
- ios/fastlane/Fastfile
Update Xcode version for CI (will get rid of that email we get from Apple)
Fix archiving of dsym
Upload release build dsyms to fabric
> CI updates

- App/features/contacts/sagas.ts
maybe not as elegant as we could be, but without getting too complicated right away, it just clear between each phrase change
fixes: https://github.com/textileio/textile-mobile/issues/977
> clears search with each phrase change

- App/Components/photo.tsx
- App/Containers/PhotoScreen.tsx
- App/screens/group/group.tsx
- package.json
- yarn.lock
Tap Image => Pinch zoom => Tap image put away
fixes https://github.com/textileio/textile-mobile/issues/1006
fixes https://github.com/textileio/textile-mobile/issues/514
fixes https://github.com/textileio/textile-mobile/issues/603
> Pinch zoom view

- App/Containers/FeedList/index.js
- App/Redux/NotificationsRedux.ts
all unread first, sorted by date. followed by all read, sorted by date
fixes https://github.com/textileio/textile-mobile/issues/1007
> Notification list ordering

- App/Services/CameraRoll.ts
fixes https://github.com/textileio/textile-mobile/issues/887
fixes https://github.com/textileio/textile-mobile/issues/962
> Ensure app doesn't create duplicate photo copies on android

- App/Components/Avatar.tsx
- App/Containers/App.tsx
- App/Containers/Groups.tsx
- App/Redux/PreferencesRedux.ts
- App/Services/EventHandlers/LocationEventHandler.ts
- android/app/src/main/AndroidManifest.xml
this covers 3/4 of the cases. one case it doesn't cover yet is, user disables location again at the system level, the app will still show it enabled in the app. 
fixes https://github.com/textileio/textile-mobile/issues/408
> Re-enables location permission prompt

- App/Containers/WalletPicker.js
in recent photos, it's been confusing me
> orders recent photos by date added

- App/Containers/App.tsx
when re-enabling, i missed that the setup steps have actually been moved to the RootContainer, 
https://github.com/textileio/textile-mobile/blob/master/App/Containers/RootContainer.tsx
> fixes location services setup

- App/Components/Avatar.tsx
- App/Components/ProgressiveImage.tsx
- App/Components/TextileImage.tsx
- App/Components/photo.tsx
…pe images are explicitly set; reduces the shouldUpdate calls on textileimage types
> Cleans up image loading for Android

- App/features/contacts/sagas.ts
fixes 1/2 of https://github.com/textileio/textile-mobile/issues/1020
> uses the invite landing not app stores

- App/Services/CameraRoll.ts
- android/app/src/main/AndroidManifest.xml
possible fix for https://github.com/textileio/textile-mobile/issues/1041#issuecomment-484527900
> reverting permissions reductions that may be needed in older android

- App/Sagas/Account/AccountSagas.ts
- App/Sagas/PhotoViewingSagas.ts
- App/Sagas/TextileEventsSagas.ts
- App/Sagas/ThreadsSagas.ts
- App/features/contacts/sagas.ts
- ios/Podfile.lock
- ios/Pods/Local Podspecs/textile-react-native-sdk.podspec.json
- ios/Pods/Manifest.lock
- ios/Pods/Pods.xcodeproj/project.pbxproj
- ios/Pods/Textile/Textile/Classes/AccountApi.m
- ios/Pods/Textile/Textile/Classes/CafesApi.m
- ios/Pods/Textile/Textile/Classes/ContactsApi.m
- ios/Pods/Textile/Textile/Classes/FeedApi.m
- ios/Pods/Textile/Textile/Classes/FilesApi.h
- ios/Pods/Textile/Textile/Classes/FilesApi.m
- ios/Pods/Textile/Textile/Classes/InvitesApi.m
- ios/Pods/Textile/Textile/Classes/MessagesApi.m
- ios/Pods/Textile/Textile/Classes/NotificationsApi.m
- ios/Pods/Textile/Textile/Classes/ProfileApi.h
- ios/Pods/Textile/Textile/Classes/ProfileApi.m
- ios/Pods/Textile/Textile/Classes/SchemasApi.m
- ios/Pods/Textile/Textile/Classes/TextileApi.m
- ios/Pods/Textile/Textile/Classes/ThreadsApi.m
- ios/Pods/TextileCore/Mobile.framework/Versions/A/Headers/Core.objc.h
- ios/Pods/TextileCore/Mobile.framework/Versions/A/Headers/Mobile.objc.h
- ios/Pods/TextileCore/Mobile.framework/Versions/A/Mobile
- ios/Textile/AppDelegate.h
- package.json
- yarn.lock
Includes go-textile 0.1.13-rc4.
**_Avatars are broken in here currently_**, but want to get this out ASAP so we can evaluate updates to the IPFS node that @sanderpick made.
Fixing avatars will require some work with @sanderpick and I'm planning to chat with him today about that.
> RN SDK 1.2.3

- App/Components/Styles/ContactModal.tsx
- App/Containers/AddContact.tsx
- App/Containers/Contact.tsx
- App/Containers/Contacts.tsx
- App/features/contacts/actions.ts
- App/features/contacts/models.ts
- App/features/contacts/reducer.ts
- App/features/contacts/sagas.ts
- package-lock.json
Fixes #1051. Adds the ability to remove a contact from the `Contact` detail view/modal. To this end, I made a few other notable changes:
- The `Contact` view now accepts an `IContact` object as a parameter, instead of `avatar`, `username`, and `address`.
- There is now a button in the `Contact` view that will let the user add a contact (if it is not already in the user's contacts) or remove a contact (if it is).
- The Contact profile layout is now vertical, not horizontal, so that more functionality can be added without disrupting the layout.
> Adds Remove Contacts Functionality

- .circleci/config.yml
> remove some old commands that are causing failure

- App/Components/Avatar.tsx
Signed-off-by: Sander Pick <sanderpick@gmail.com>
> avatars: d -> content

- .circleci/config.yml
> Update to Xcode 10.2.0 image

- App/Components/message.tsx
- package.json
- typings/typings.d.ts
- yarn.lock
Fixes #1072. Uses [react-native-hyperlink](https://github.com/obipawan/react-native-hyperlink) to handle detecting links and making them clickable cross-platform.
> Make Links Clickable

- .circleci/config.yml
> Revert to older xcode for adhoc ios

- App/Components/Avatar.tsx
this one is critical to get into the release @asutula
> fixes locally pulled avatar

- android/app/build.gradle
> sets flag to true

- App/Navigation/AppNavigation/Modal/Settings/index.ts
- App/SB/views/UserProfile/index.tsx
- App/features/account/selectors.ts
- App/screens/cafe-session.tsx
- App/screens/cafes.tsx
- package.json
- yarn.lock
Have some insight into your cafe sessions, refresh them if you want.
Super basic utility screens for now, only shown in verbose UI mode from the settings menu.
When you're looking at the details of a session, tap a row to copy it's value to the clipboard to send to @sanderpick for troubleshooting.
> Cafes verbose ui

- App/Components/Avatar.tsx
> removes force cache from avatar requests

- App/features/contacts/selectors.ts
> filter all except earliest copy of a duplicate search result

- android/build.gradle
- ios/Textile.xcodeproj/project.pbxproj
Will use it to trigger a new beta build
> Little change while updating certs repo

- android/app/build.gradle
> Only enable separate builds on release builds

- App/screens/group/group.tsx
> Don't crash if selecting cancel

- package.json
- yarn.lock
> sdk: bump v2.1.4

- App/Components/Loading.tsx
- App/Containers/App.tsx
- App/Containers/ChooseCafe.tsx
- App/Containers/RegisterCafe.tsx
- App/Containers/StatusCheck.tsx
Or else you get an error for sure. Looks like:
> Register cafe: Block until online

- ios/Podfile.lock
- ios/Pods/Local Podspecs/textile-react-native-sdk.podspec.json
- ios/Pods/Manifest.lock
- ios/Pods/Pods.xcodeproj/project.pbxproj
- package.json
- yarn.lock
> Update to rn sdk 2.1.7

- android/fastlane/Fastfile
This will hopefully fix the problem of the Beta app getting uninstalled each time you update
> Upload only 64 bit apk to Fabric

- ios/fastlane/Fastfile
> Don't disable UIFileSharingEnabled for prod release

- App/screens/group/group.tsx
> fixes type check to allow for possible nulls

- package.json
- yarn.lock
> Lock down reanimated version

- App/Containers/Contact.tsx
- App/Redux/PhotoViewingSelectors.ts
This fixes #1245. I've gone through the whole process and verified that it is working as intended with this sharing setting. However, when I was testing I still encountered the #1260 bug.
> Fix sharing setting of p2p threads.

- App/Components/photo.tsx
- App/features/cafes/sagas.ts
This is part I of III.
I went ahead and tried the 'reregister' with new cafe step because I didn't see any downside. worse case is that it fails silently and my next work will still matter. best case is that my next work wont matter (notify users of need to register a cafe).
> attempts to deregister and register in a catch

- App/features/cafes/sagas.ts
- ios/fastlane/Fastfile
fixes identified on our call @asutula
> Switch to requesting sessions right from node

- App/Services/ErrorHandler.ts
- android/app/build.gradle
- android/app/src/main/java/com/textile/MainApplication.java
- android/build.gradle
- android/settings.gradle
- ios/Textile.xcodeproj/project.pbxproj
- package.json
- yarn.lock
We can use react-native-firebase to achieve the same things
> Remove old fabric native module

- .circleci/config.yml
- android/app/build.gradle
- android/fastlane/Fastfile
> use xlarge ci machine for android adhoc

- App/Sagas/index.ts
> remove test event

- App/Containers/Cafe.tsx
fixes https://github.com/textileio/photos/issues/1264
maybe not the most elegant, but it just needs to deal with those two params being null for a microsecond before it navigates the user back to the registration page
> fixes bug where app crashes on cafe deregister

- .circleci/config.yml
- android/fastlane/Fastfile
> Better mem settings for android release

- ios/NativeViews/TextileImageView.m
> needs re-render should only be false after a successful rendering

- App/screens/group/group.tsx
there is a bug where the actionsheet was missing the 'remove' button and 'cancel' would actually lead to the image being removed.
this was due to,
1. action sheet being shown before the state was updated, so it was missing the data about which photo was selected. 
2. because no photo selected, it would not be removable, so no remove option
3. then the state would update, changing the index of where cancel should be and remove should be in the button list
4. but since the actionsheet isn't an updatable view, there would still only be a 'cancel' button, at index 0 where 'remove' should be now that the state is update.
anyway... this fixes it by just showing the action sheet _after_ the state is updated
> Fixes image remove actionsheet

- App/Containers/FeedList/Alerts.tsx
- App/Containers/RegisterCafe.tsx
- App/features/updates/actions.ts
- App/features/updates/models.ts
- App/features/updates/reducer.ts
- App/features/updates/sagas.ts
- App/features/updates/selectors.ts
> fixes a couple of small issues

- package.json
- yarn.lock
> Fixes crash on comment in android
